sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mmadiawetsa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mmadiawetsa/docker-react npm run test

 # travis configuration for deployment 
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  # name of the app
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-425917868831'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
